//! Embedded icons, decoded once at startup. Generated by `app/scripts/gen_icons.py`.

use std::sync::OnceLock;

/// Which tray picture to show.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayKind {
    Idle,
    Syncing,
    Paused,
    Error,
    Offline,
    SignedOut,
}

const TRAY_PNGS: [(TrayKind, &[u8]); 6] = [
    (TrayKind::Idle, include_bytes!("../icons/tray-idle.png")),
    (TrayKind::Syncing, include_bytes!("../icons/tray-syncing.png")),
    (TrayKind::Paused, include_bytes!("../icons/tray-paused.png")),
    (TrayKind::Error, include_bytes!("../icons/tray-error.png")),
    (TrayKind::Offline, include_bytes!("../icons/tray-offline.png")),
    (TrayKind::SignedOut, include_bytes!("../icons/tray-signedout.png")),
];

const APP_PNG: &[u8] = include_bytes!("../icons/128x128.png");

struct Rgba {
    width: u32,
    height: u32,
    data: Vec<u8>,
}

/// Decodes a PNG into 8-bit RGBA.
fn decode(bytes: &[u8]) -> Option<Rgba> {
    let mut decoder = png::Decoder::new(std::io::Cursor::new(bytes));
    decoder.set_transformations(png::Transformations::EXPAND | png::Transformations::STRIP_16);
    let mut reader = decoder.read_info().ok()?;
    let mut buf = vec![0; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).ok()?;
    buf.truncate(info.buffer_size());
    let data = match info.color_type {
        png::ColorType::Rgba => buf,
        png::ColorType::Rgb => buf.chunks_exact(3).flat_map(|p| [p[0], p[1], p[2], 255]).collect(),
        png::ColorType::GrayscaleAlpha => buf.chunks_exact(2).flat_map(|p| [p[0], p[0], p[0], p[1]]).collect(),
        png::ColorType::Grayscale => buf.iter().flat_map(|&g| [g, g, g, 255]).collect(),
        png::ColorType::Indexed => return None, // EXPAND turns palettes into RGB(A)
    };
    Some(Rgba { width: info.width, height: info.height, data })
}

/// Tray pixmaps in the StatusNotifierItem format (ARGB32, network byte order).
pub fn tray_pixmap(kind: TrayKind) -> Vec<ksni::Icon> {
    static CACHE: OnceLock<Vec<(TrayKind, ksni::Icon)>> = OnceLock::new();
    let cache = CACHE.get_or_init(|| {
        TRAY_PNGS
            .iter()
            .filter_map(|(k, bytes)| {
                let img = decode(bytes)?;
                let mut data = img.data;
                for px in data.chunks_exact_mut(4) {
                    px.rotate_right(1); // RGBA -> ARGB
                }
                Some((
                    *k,
                    ksni::Icon { width: img.width as i32, height: img.height as i32, data },
                ))
            })
            .collect()
    });
    cache
        .iter()
        .filter(|(k, _)| *k == kind)
        .map(|(_, icon)| icon.clone())
        .collect()
}

pub fn window_icon() -> Option<tauri::image::Image<'static>> {
    let img = decode(APP_PNG)?;
    Some(tauri::image::Image::new_owned(img.data, img.width, img.height))
}
